document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\"UTF-8\">");
document.writeln("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
document.writeln("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("<title>清梦</title>");
document.writeln("<link rel=\"stylesheet\" href=\"../css1/b_cover.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<audio id=\"music\" autoplay=\"autoplay\" loop=\"loop\" src=\"../music/多谢泪的告白.mp3\">");
document.writeln("</audio>");
document.writeln("<div class=\"home\">");
document.writeln("<div class=\"content\">");
document.writeln("<div class=\"stars\"></div>");
document.writeln("<div class=\"centt\">");
document.writeln("<div class=\"cent\"></div>");
document.writeln("<img class=\"avatar_size\" src=\"../images/avater.jpg\" alt=\"\" onclick=\"musiccc()\">");
document.writeln("<h3 class=\"title\">清梦</h3>");
document.writeln("<div class=\"NET\">");
document.writeln("<ul>");
document.writeln("<li><a href=\"../index.html\"  class=\"\">首页</a></li>");
document.writeln("<li><a href=\"#\" class=\"\">文章</a></li>");
document.writeln("<li><a href=\"#\" class=\"\">留言</a></li>");
document.writeln("<li><a href=\"#\" class=\"\">关于作者</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<div class=\"PC\">");
document.writeln("<button class=\"dropbtn\">菜单</button>");
document.writeln("<div class=\"PC-content\">");
document.writeln("<a href=\"../index.html\">首页</a>");
document.writeln("<a href=\"#\">文章</a>");
document.writeln("<a href=\"#\">留言</a>");
document.writeln("<a href=\"#\">关于作者</a>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<img class=\"bga\" src=\"../images/bg_shu.png\" width=\"100%\" alt=\"\">");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("<script type=\"text/javascript\" src=\"../js/music.js\"></script>");
document.writeln("</html>");